sudo: false

language: python
python:
  - "2.7"

os:
  - linux

script:
  - echo -e "travis_fold:start:sketch_test_env_prepare"
  - pip install pyserial
  - wget -O arduino.tar.xz https://www.arduino.cc/download.php?f=/arduino-nightly-linux64.tar.xz
  - tar xf arduino.tar.xz
  - mv arduino-nightly $HOME/arduino_ide
  - mkdir -p $HOME/Arduino/libraries
  - cd $HOME/arduino_ide/hardware
  - mkdir espressif
  - cd espressif
  - git clone https://github.com/espressif/arduino-esp32.git esp32
  - cd esp32/tools
  - python get.py
  - export PATH="$HOME/arduino_ide:$HOME/arduino_ide/hardware/espressif/esp32/tools/xtensa-esp32-elf/bin:$PATH"
  - which arduino
  - cd $HOME/Arduino/libraries
  - git clone https://github.com/bbx10/WebServer_tng ${HOME}/Arduino/libraries/WebServer
  - echo -e "travis_fold:end:sketch_test_env_prepare"
  - echo -e "travis_fold:start:sketch_test"
  - BOARD="espressif:esp32:esp32"
  - cd ${HOME}/Arduino/libraries/WebServer/examples
  - arduino --verbose-build --verify --board ${BOARD} HelloServer/HelloServer.ino
  - arduino --verbose-build --verify --board ${BOARD} SDWebServer/SDWebServer.ino
  - arduino --verbose-build --verify --board ${BOARD} SimpleAuthentification/SimpleAuthentification.ino
  - arduino --verbose-build --verify --board ${BOARD} FSBrowser/FSBrowser.ino
  - arduino --verbose-build --verify --board ${BOARD} WebUpdate/WebUpdate.ino
  - arduino --verbose-build --verify --board ${BOARD} AdvancedWebServer/AdvancedWebServer.ino
  - arduino --verbose-build --verify --board ${BOARD} HttpBasicAuth/HttpBasicAuth.ino
  - echo -e "travis_fold:end:sketch_test"

notifications:
  email:
    on_success: change
    on_failure: change    
